services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: "1000:1000"
    volumes:
      - ./config:/config
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
