commands:
  dry_run: true # CAREFUL
  cross_seed: false
  recheck: false
  cat_update: true
  tag_update: true
  rem_unregistered: false
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: true
  share_limits: true
  skip_qb_version_check: false
  skip_cleanup: false

qbt:
  host: localhost:8080
  user: YOUR_USER
  pass: "YOUR_PASS_HERE"

settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  nohardlinks_tag: noHL
  share_limits_tag: ~share_limit
  cross_seed_tag: cross-seed
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
  cat_update_all: true
  disable_qbt_default_share_limits: true
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  force_auto_tmm_ignore_tags: []

directory:
  root_dir: /media/downloads/torrents
  recycle_bin: /media/.RecycleBin
  torrents_dir: /qbittorrent/config/qBittorrent/BT_backup
  orphaned_dir: /media/orphaned_data
  cross_seed: /media/downloads/torrents/cross_seed
  remote_dir: /media/downloads/torrents/

cat:
  All: /media/downloads/torrents/
  radarr: /media/Movies/
  tv-sonarr: /media/Shows/
  Shows: /media/Shows/
  Movies: /media/Movies/
  downloads: /downloads/

nohardlinks:
  - radarr
  - tv-sonarr

recyclebin:
  enabled: true
  empty_after_x_days: 0
  save_torrents: true
  split_by_category: false

orphaned:
  empty_after_x_days: 7
  exclude_patterns:
    - "**/.DS_Store"
    - "**/Thumbs.db"
    - "**/@eaDir"
    - /media/downloads/torrents/temp/**
    - "**/*.!qB"
    - "**/*_unpackerred"
  max_orphaned_files_to_delete: 50

share_limits:
  low_seeders:
    priority: 1
    max_num_seeds: 5
    max_ratio: -1
    max_seeding_time: -1
    limit_upload_speed: -1
    last_active: 30d
    add_group_to_tag: true
    custom_tag: low_seeders
    cleanup: false
  high_seeders:
    priority: 2
    min_num_seeds: 6
    max_ratio: 3.0
    max_seeding_time: 30d
    limit_upload_speed: 500
    min_seeding_time: 7d
    last_active: 14d
    add_group_to_tag: true
    custom_tag: high_seeders
    cleanup: false
  noHL:
    priority: 0
    include_all_tags:
      - noHL
    cleanup: true
    max_ratio: 1
    max_seeding_time: 0
  default:
    priority: 999
    max_ratio: 2.0
    max_seeding_time: 14d
    limit_upload_speed: 250
    min_seeding_time: 3d
    last_active: 7d
    add_group_to_tag: true
    custom_tag: default_seeders
    cleanup: false

webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    share_limits:
    cleanup_dirs:
