services:
 radarr:
   image: linuxserver/radarr:latest
   container_name: radarr
   environment:
     - PUID=1000
     - PGID=1000
     - TZ=America/Chicago
   volumes:
     - ./config:/config
     - /path/to/media:/media
   ports:
     - "7878:7878"
   restart: unless-stopped