  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
     - ./config:/config
     - /path/to/media:/media # Update to your media directory
    ports:
      - 8989:8989
    restart: unless-stopped
