services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    user: "1000:1000"
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared
    restart: unless-stopped
    ports:
      - "2000:2000"
    networks:
      - monitor-net

networks:
  monitor-net:
    external: true
    name: monitoring_monitor-net
