services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8000:80/tcp"
    environment:
      - TZ=America/Chicago
      - WEBPASSWORD=YOUR_PIHOLE_PASSWORD
      - PIHOLE_DNS_1=1.1.1.1
      - PIHOLE_DNS_2=1.0.0.1
    dns:
      - YOUR_ROUTER_IP
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
